### ISSUE TITLE
improved code/ gui calculator

### ISSUE THREAD

**Issue by MohammadJavadTabari** [Dayana-World/Dayana-Python-Lab#12]

**Comment by MohammadJavadTabari** [comment]
@mostafakavand  plz write description for your jobs. thanks man

**Comment by mostafakavand** [comment]
A graphical calculator  written with the Tkinter Python library.
This calculator is located at this [address](https://github.com/Dayana-World/Dayana-Python-Lab/tree/main/Dayana%20python%20lab/0_Education/0_education_play_ground/00_code_lak)
