### ISSUE TITLE
Dayana Python Lab /  hi py game / Convert all Persian comments to english

### ISSUE THREAD

**Issue by MohammadJavadTabari** [Dayana-World/Dayana-Python-Lab#26]
convert all persian comments in hi py game to english,
force team mates to read english.
this is neccessary

**Comment by mostafakavand** [comment]
Yes, everyone really needs to learn English

**Comment by mostafakavand** [comment]
Done. If there is something wrong, please tell me

**Comment by mostafakavand** [comment]
Done. If there is something wrong, please tell me

**Comment by MohammadJavadTabari** [comment]
> Done. If there is something wrong, please tell me

everything  is ok
