### ISSUE TITLE
Dayana Python Lab / hi py game / Review Game parts and levels / find a way to improve it

### ISSUE THREAD

**Issue by MohammadJavadTabari** [Dayana-World/Dayana-Python-Lab#27]
analyze "hi py game" concept and goals,
there is better codes and ways to teach people for sure 
find them and give us your idea.
try write it english,  this will be published on dayana posts

**Comment by HosseinChoopani** [comment]
Here are some points (not technical ones):
We don't give instructions to users for sending us their practice files (such as a link or an email address) 
we have two copies of the codes in some hi_py game levels
There are some typos and writing issues:
-----part1/level1 line9: it seems "he writes" should be "you write"
-----part2/level5 line4: it seems "theme" should be "them"
-----part1/level6 line3: is there an education (knowledge) team anymore?
-----part1/level2 line15: an unnecessary "S" after "!"
the comments (not instructions) in part1/level2 seem unnecessary
files in part 1 are not in the correct ascending order
it is so good that there are several ideas for each level in part 3. these ideas are inspiring.

**Comment by MohammadJavadTabari** [comment]
> Here are some points (not technical ones): We don't give instructions to users for sending us their practice files (such as a link or an email address) we have two copies of the codes in some hi_py game levels There are some typos and writing issues: -----part1/level1 line9: it seems "he writes" should be "you write" -----part2/level5 line4: it seems "theme" should be "them" -----part1/level6 line3: is there an education (knowledge) team anymore? -----part1/level2 line15: an unnecessary "S" after "!" the comments (not instructions) in part1/level2 seem unnecessary files in part 1 are not in the correct ascending order it is so good that there are several ideas for each level in part 3. these ideas are inspiring.

thanks man.
please fix typo first.
and the practice result that you said. this is my big issue, i think email can be good. 
if you are agree with me, write the instruction in guides file and use this outlook email
Dayana_Organization@outlook.com
