### ISSUE TITLE
my bad/ my mistake/ see description

### ISSUE THREAD

**Issue by MohammadJavadTabari** [Dayana-World/Dayana-Python-Lab#37]
please redo "convert persian to english" task, i remove it in conflict resolving by mistake, sorry man send pr again

**Comment by mostafakavand** [comment]
This work was performed

**Comment by mostafakavand** [comment]
Good thing I hadn't synced my fork. And if not, the files had to be translated again

**Comment by MohammadJavadTabari** [comment]
> Good thing I hadn't synced my fork. And if not, the files had to be translated again

so now send pr and this should be ok

**Comment by mostafakavand** [comment]
I sent four hours ago

**Comment by MohammadJavadTabari** [comment]
> I sent four hours ago

is done, i see, well done boy

**Comment by MohammadJavadTabari** [comment]
> I sent four hours ago

if i had 3 person like you, at this time we could start our project

**Comment by mostafakavand** [comment]
> > I sent four hours ago
> 
> if i had 3 person like you, at this time we could start our project

I am still trying to find suitable people for this job among my acquaintances.
